// Exercises src/x402-handler.mjs's real payer path end to end against the
// localhost stub facilitator (test/stub-x402-facilitator.mjs), the same way
// DEPLOYMENT.md's "settlement remains untested" gap is closed for a real
// deploy: build payment requirements the way the worker's `withX402` does
// (x402ResourceServer + registerExactEvmScheme, both from the worker's own
// dependencies), sign a payment with payX402() using a throwaway key
// generated fresh for this test run, then verify and settle that payment
// against the stub the same way the worker would.
//
// No private key is ever written to a file or logged - it lives only in
// process.env for the duration of this test, generated by viem.
//
// This proves the buyer's payload is well-formed and reaches the same
// verify/settle code path the worker uses in production. It does not prove
// a real Base Sepolia transaction cleared - the stub facilitator never talks
// to a chain (see its file header). Run against the real facilitator per
// the README ("Wiring a real x402 payer") to prove that.

import assert from "node:assert/strict";
import { test } from "node:test";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";

import { registerExactEvmScheme } from "@x402/evm/exact/server";
import { x402ResourceServer, HTTPFacilitatorClient } from "@x402/core/server";

import { createStubFacilitator } from "./stub-x402-facilitator.mjs";

const PAYOUT_ADDRESS = "0xbBA79C2D92FD6fe815602e29E81Da27aB23E705D";
const NETWORK = "eip155:84532";

async function withStubFacilitator(fn) {
  const server = createStubFacilitator();
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const { port } = server.address();
  try {
    return await fn(`http://127.0.0.1:${port}`);
  } finally {
    await new Promise((resolve) => server.close(resolve));
  }
}

function buildResourceServer(facilitatorUrl) {
  const resourceServer = new x402ResourceServer(new HTTPFacilitatorClient({ url: facilitatorUrl }));
  registerExactEvmScheme(resourceServer);
  return resourceServer;
}

test("hasPayer() is false with no BUYER_PRIVATE_KEY set", async () => {
  delete process.env.BUYER_PRIVATE_KEY;
  const { hasPayer, payX402 } = await import("../src/x402-handler.mjs?no-payer");
  assert.equal(hasPayer(), false);
  // With no requirements needed either, since it should bail before using them.
  assert.equal(await payX402([{ scheme: "exact", network: NETWORK }]), null);
});

test("payX402 signs a payment that the resource server verifies and settles via the stub facilitator", async () => {
  await withStubFacilitator(async (facilitatorUrl) => {
    const resourceServer = buildResourceServer(facilitatorUrl);
    await resourceServer.initialize();

    const requirements = await resourceServer.buildPaymentRequirements({
      scheme: "exact",
      payTo: PAYOUT_ADDRESS,
      price: "0.25",
      network: NETWORK,
      maxTimeoutSeconds: 300,
    });

    // A throwaway key generated fresh for this run only - never written
    // anywhere, never reused, discarded when the process exits.
    const privateKey = generatePrivateKey();
    process.env.BUYER_PRIVATE_KEY = privateKey;
    const expectedAddress = privateKeyToAccount(privateKey).address;

    const { hasPayer, payX402 } = await import("../src/x402-handler.mjs?with-payer");
    assert.equal(hasPayer(), true);

    const challenge = {
      x402Version: 2,
      error: "PAYMENT_REQUIRED",
      resource: { url: "x402://drift_report_x402", description: "test", mimeType: "application/json" },
      accepts: requirements,
    };

    const token = await payX402(requirements, challenge);
    assert.equal(typeof token, "string");

    const paymentPayload = JSON.parse(Buffer.from(token, "base64").toString("utf8"));
    assert.equal(paymentPayload.x402Version, 2);
    assert.equal(paymentPayload.payload.authorization.from, expectedAddress);
    assert.match(paymentPayload.payload.signature, /^0x[0-9a-fA-F]+$/);

    const matchingReq = resourceServer.findMatchingRequirements(requirements, paymentPayload);
    assert.ok(matchingReq, "resource server should find a matching requirement for the signed payload");

    const verifyResult = await resourceServer.verifyPayment(paymentPayload, matchingReq);
    assert.equal(verifyResult.isValid, true, JSON.stringify(verifyResult));
    assert.equal(verifyResult.payer, expectedAddress);

    const settleResult = await resourceServer.settlePayment(paymentPayload, matchingReq);
    assert.equal(settleResult.success, true, JSON.stringify(settleResult));
    assert.equal(settleResult.payer, expectedAddress);
    assert.match(settleResult.transaction, /^0x[0-9a-fA-F]+$/);
    assert.equal(settleResult.network, NETWORK);

    delete process.env.BUYER_PRIVATE_KEY;
  });
});
